# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 1psconstructor
from __future__ import annotations


GROUND = (0.08, 0.08, 0.10)

INK = (0.92, 0.92, 0.94)
INK_MUTED = (0.65, 0.65, 0.70)
INK_FAINT = (0.43, 0.43, 0.49)
LINE = (0.30, 0.30, 0.35)

ACCENT = (0.20, 0.52, 0.90)
ACCENT_INK = (0.75, 0.85, 0.95)

GOOD = (0.20, 0.78, 0.35)
WARN = (0.97, 0.63, 0.00)
BAD = (0.88, 0.11, 0.14)

ALPHA_SOFT = 0.30
ALPHA_GHOST = 0.16
ALPHA_PLATE = 0.72


def rgba(colour: tuple[float, float, float], alpha: float) -> tuple[float, float, float, float]:
    red, green, blue = colour
    return red, green, blue, alpha


FONT_FAMILY = "sans"
FONT_FAMILY_DATA = "monospace"

DISPLAY = 28
TITLE = 22
BODY = 16
LABEL = 14
DATA = 10


SPACING = (4, 8, 12, 16, 24, 32, 48)

EDGE = 60
PLATE_GAP = 32
PLATE_PADDING = 16

RADIUS_SMALL = 6
RADIUS_PLATE = 10


FADE_FROM_LIGHT = (0.98, 0.98, 0.99)
FADE_MS = 120


def opening_ground(elapsed_ms: float, dark_desktop: bool,
                   animate: bool = True) -> tuple[float, float, float]:
    if dark_desktop or not animate or elapsed_ms >= FADE_MS:
        return GROUND
    progress = max(0.0, elapsed_ms) / FADE_MS
    return tuple(                                    # type: ignore[return-value]
        start + (end - start) * progress
        for start, end in zip(FADE_FROM_LIGHT, GROUND)
    )


def desktop_is_dark() -> bool:
    try:
        import gi
        gi.require_version("Adw", "1")
        from gi.repository import Adw

        return bool(Adw.StyleManager.get_default().get_dark())
    except Exception:                                # pragma: no cover - no GTK
        return True


def animations_enabled() -> bool:
    try:
        import gi
        gi.require_version("Gtk", "4.0")
        from gi.repository import Gtk

        settings = Gtk.Settings.get_default()
        if settings is None:
            return False
        return bool(settings.get_property("gtk-enable-animations"))
    except Exception:                                # pragma: no cover - no GTK
        return False


def residual_colour(residual: float) -> tuple[float, float, float]:
    if residual < 0.02:
        return GOOD
    if residual < 0.05:
        return WARN
    return BAD


def residual_radius(residual: float) -> float:
    return max(8.0, min(40.0, 8.0 + residual * 500))


SURFACE = "#1B1B22"
SURFACE_2 = "#23232C"
SURFACE_3 = "#2C2C37"

INK_CSS = "#EBEBF0"
INK_MUTED_CSS = "#A6A6B3"
INK_FAINT_CSS = "#6E6E7D"
LINE_CSS = "#3A3A45"
ACCENT_CSS = "#3385E6"
GOOD_CSS = "#33C759"
WARN_CSS = "#F7A100"
BAD_CSS = "#E01C24"

GOOD_SOFT = "rgba(51, 199, 89, 0.14)"
WARN_SOFT = "rgba(247, 161, 0, 0.14)"
BAD_SOFT = "rgba(224, 28, 36, 0.14)"

CONTENT_WIDTH = 840
DETAIL_WIDTH = 640


def css(dark: bool) -> str:
    if dark:
        surface_2 = SURFACE_2
        surface_3 = SURFACE_3
        ink = INK_CSS
        ink_muted = INK_MUTED_CSS
        ink_faint = INK_FAINT_CSS
        line = LINE_CSS
        window = SURFACE
    else:
        surface_2 = "@card_bg_color"
        surface_3 = "shade(@card_bg_color, 0.94)"
        ink = "@window_fg_color"
        ink_muted = "alpha(@window_fg_color, 0.75)"
        ink_faint = "alpha(@window_fg_color, 0.55)"
        line = "@borders"
        window = "@window_bg_color"

    return f"""
/* Generated by gui/design.py: change the values there, not here. */

window.osg-settings,
window.osg-settings headerbar {{
  background: {window};
}}

/* --- the 3x2 card grid ------------------------------------------------ */

button.osg-card {{
  background: {surface_2};
  border: none;
  box-shadow: none;
  border-radius: {RADIUS_PLATE}px;
  padding: {SPACING[3]}px;
}}
button.osg-card:hover {{
  background: {surface_3};
}}

.osg-card-title {{
  font-size: {BODY}px;
  font-weight: 700;
  color: {ink};
}}
.osg-card-desc {{
  font-size: {LABEL}px;
  color: {ink_faint};
}}

/* --- chips ------------------------------------------------------------ */

.osg-chip {{
  font-size: {DATA}px;
  font-weight: 700;
  padding: 3px 9px;
  border-radius: 999px;
  background: {surface_3};
  color: {ink_muted};
}}
.osg-chip.good {{ background: {GOOD_SOFT}; color: {GOOD_CSS}; }}
.osg-chip.warn {{ background: {WARN_SOFT}; color: {WARN_CSS}; }}
.osg-chip.bad  {{ background: {BAD_SOFT};  color: {BAD_CSS}; }}

/* --- pill buttons ----------------------------------------------------- */

button.osg-pill,
menubutton.osg-pill > button {{
  font-size: {LABEL}px;
  font-weight: 700;
  color: {ink_muted};
  background: {surface_2};
  border: 1px solid {line};
  border-radius: 999px;
  padding: 5px 12px;
  min-height: 0;
  box-shadow: none;
}}
button.osg-pill:hover,
menubutton.osg-pill > button:hover {{
  color: {ink};
  background: {surface_3};
}}
button.osg-pill.small,
menubutton.osg-pill.small > button {{
  font-size: {DATA}px;
  padding: 3px 9px;
}}

/* --- headings and running text ---------------------------------------- */

.osg-h1     {{ font-size: {TITLE}px; font-weight: 700; color: {ink}; }}
.osg-lead   {{ font-size: {LABEL}px; color: {ink_faint}; }}
.osg-status {{ font-size: {LABEL}px; color: {ink_faint}; }}
.osg-name   {{ font-size: {LABEL}px; font-weight: 700; color: {ink_muted}; }}

/* --- the status dots, and the one in the connection line -------------- */

.osg-dot {{
  min-width: 12px;
  min-height: 12px;
  border-radius: 999px;
  background: {surface_3};
}}
.osg-dot.small {{ min-width: 8px; min-height: 8px; }}
.osg-dot.good  {{ background: {GOOD_CSS}; }}
.osg-dot.warn  {{ background: {WARN_CSS}; }}
.osg-dot.bad   {{ background: {BAD_CSS}; }}

/* --- the donation footer ---------------------------------------------- */

.osg-footer {{
  border-top: 1px solid {line};
  background: {window};
  padding: {SPACING[1]}px {SPACING[3]}px;
}}
"""


_provider = None


def load_css(display=None) -> None:
    global _provider

    import gi
    gi.require_version("Gtk", "4.0")
    gi.require_version("Adw", "1")
    from gi.repository import Adw, Gdk, Gtk

    if display is None:
        display = Gdk.Display.get_default()
    if display is None:                              # pragma: no cover - no GTK
        return

    manager = Adw.StyleManager.get_default()

    if _provider is None:
        _provider = Gtk.CssProvider()
        Gtk.StyleContext.add_provider_for_display(
            display, _provider,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION,
        )
        manager.connect("notify::dark", lambda *_a: load_css(display))

    _provider.load_from_string(css(bool(manager.get_dark())))
