#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 1psconstructor
"""
Generate the application icon from its geometric definition.
"""
from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

SIZE = 64.0
CORNER_RADIUS = 12.0

GROUND = "#14141A"
GROUND_EDGE = "#2A2A33"
ACCENT = "#3385E6"

SYMBOLIC_PLACEHOLDER = "#BEBEBE"
SYMBOLIC_CLASS = "ColorScheme-Text"

CENTRE = (SIZE / 2, SIZE / 2)
STROKE = 3.0

EYE_RADIUS = 5.0

ORBIT_RX = SIZE / 2 - CORNER_RADIUS
ORBIT_RY = 10.0

ORBIT_ANGLE = -45.0 / 2


def eye_circle() -> str:
    return (f'<circle cx="{CENTRE[0]:.3f}" cy="{CENTRE[1]:.3f}" '
            f'r="{EYE_RADIUS:.3f}"/>')


def orbit_ellipse() -> str:
    return (f'<ellipse cx="{CENTRE[0]:.3f}" cy="{CENTRE[1]:.3f}" '
            f'rx="{ORBIT_RX:.3f}" ry="{ORBIT_RY:.3f}" '
            f'transform="rotate({ORBIT_ANGLE:.3f} {CENTRE[0]:.3f} {CENTRE[1]:.3f})"/>')


HEADER = ("<!-- Generated by scripts/build-icon.py: edit the geometry there,"
          " not this file. -->")


def app_icon() -> str:
    return f"""<?xml version="1.0" encoding="UTF-8"?>
{HEADER}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE:.0f} {SIZE:.0f}"
     width="{SIZE:.0f}" height="{SIZE:.0f}">
  <defs>
    <linearGradient id="tile" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="{GROUND_EDGE}"/>
      <stop offset="1" stop-color="{GROUND}"/>
    </linearGradient>
  </defs>
  <rect x="0" y="0" width="{SIZE:.0f}" height="{SIZE:.0f}"
        rx="{CORNER_RADIUS:.0f}" ry="{CORNER_RADIUS:.0f}" fill="url(#tile)"/>
  <rect x="0.5" y="0.5" width="{SIZE - 1:.0f}" height="{SIZE - 1:.0f}"
        rx="{CORNER_RADIUS - 0.5:.1f}" ry="{CORNER_RADIUS - 0.5:.1f}"
        fill="none" stroke="{GROUND_EDGE}" stroke-width="1" opacity="0.9"/>
  <g fill="none" stroke="{ACCENT}" stroke-width="{STROKE}"
     stroke-linecap="round" stroke-linejoin="round">
    {eye_circle()}
    {orbit_ellipse()}
  </g>
</svg>
"""


def symbolic_icon() -> str:
    return f"""<?xml version="1.0" encoding="UTF-8"?>
{HEADER}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE:.0f} {SIZE:.0f}"
     width="{SIZE:.0f}" height="{SIZE:.0f}">
  <defs>
    <style id="current-color-scheme" type="text/css">
      .{SYMBOLIC_CLASS} {{ color: {SYMBOLIC_PLACEHOLDER}; }}
    </style>
  </defs>
  <g class="{SYMBOLIC_CLASS}" fill="none" stroke="currentColor"
     stroke-width="{STROKE + 0.6:.1f}"
     stroke-linecap="round" stroke-linejoin="round">
    {eye_circle()}
    {orbit_ellipse()}
  </g>
</svg>
"""


CARD_SIZE = 20.0
CARD_STROKE = 1.6

CARD_ICONS = {
    "target": ("Calibration", """<circle cx="10" cy="10" r="6"/>
    <circle cx="10" cy="10" r="2"/>
    <path d="M10 2.5v2M10 15.5v2M2.5 10h2M15.5 10h2"/>"""),
    "stick": ("Games", """<path d="M10 6v9"/>
    <circle cx="10" cy="5" r="1.7"/>
    <rect x="6" y="15" width="8" height="2.2" rx="1.1"/>"""),
    "send": ("Output", """<path d="M3 10l14-6.5-5 14-2.5-6-6-1.5z"/>"""),
    "eye": ("Gaze preview", """<path d="M2 10s3-5.3 8-5.3 8 5.3 8 5.3-3 5.3-8 5.3-8-5.3-8-5.3z"/>
    <circle cx="10" cy="10" r="2.3"/>"""),
    "curve": ("Curves", """<path d="M3 16c4 0 3.5-11 7-11s3 11 7 11"/>
    <circle cx="3" cy="16" r="1.1" fill="{accent}" stroke="none"/>
    <circle cx="17" cy="16" r="1.1" fill="{accent}" stroke="none"/>"""),
    "gear": ("Settings", """<circle cx="10" cy="10" r="4.6"/>
    <path d="M10 3v2.3M10 14.7V17M17 10h-2.3M5.3 10H3M14.7 5.3l-1.6 1.6\
M6.9 13.1l-1.6 1.6M14.7 14.7l-1.6-1.6M6.9 6.9L5.3 5.3"/>"""),
}

PILL_INK = "#8A8A96"

PILL_ICONS = {
    "globe": ("Language", """<circle cx="10" cy="10" r="7.3"/>
    <ellipse cx="10" cy="10" rx="3.1" ry="7.3"/>
    <path d="M2.7 10h14.6M3.6 6h12.8M3.6 14h12.8"/>"""),
    "cup": ("Ko-fi", """<path d="M5 5.5h8v6.3a4 4 0 01-4 4 4 4 0 01-4-4V5.5z"/>
    <path d="M13 7.3h1.3a2 2 0 010 4H13"/>"""),
    "heart": ("Patreon", """<path d="M10 16.3S3.3 12 3.3 7.9a3.7 3.7 0 017.5-2.3\
A3.7 3.7 0 0117.7 3.3 3.7 3.7 0 0116.7 7.9c0 4.1-6.7 8.4-6.7 8.4z"/>"""),
    "chev-d": ("Drop-down", """<path d="M4.5 7.5l5.5 6 5.5-6"/>"""),
}


def _outline_icon(name: str, purpose: str, body: str, colour: str) -> str:
    return f"""<?xml version="1.0" encoding="UTF-8"?>
{HEADER}
<!-- {purpose} icon; the geometry of `i-{name}` from the settings
     overview. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {CARD_SIZE:.0f} {CARD_SIZE:.0f}"
     width="{CARD_SIZE:.0f}" height="{CARD_SIZE:.0f}">
  <g fill="none" stroke="{colour}" stroke-width="{CARD_STROKE}"
     stroke-linecap="round" stroke-linejoin="round">
    {body.format(accent=colour)}
  </g>
</svg>
"""


def card_icon(name: str) -> str:
    purpose, body = CARD_ICONS[name]
    return _outline_icon(name, purpose, body, ACCENT)


def pill_icon(name: str) -> str:
    purpose, body = PILL_ICONS[name]
    return _outline_icon(name, purpose, body, PILL_INK)


TARGETS = {
    "data/icons/openstargazer.svg": app_icon,
    "data/icons/openstargazer-symbolic.svg": symbolic_icon,
    **{f"data/icons/osg-{name}.svg": (lambda n=name: card_icon(n))
       for name in CARD_ICONS},
    **{f"data/icons/osg-{name}.svg": (lambda n=name: pill_icon(n))
       for name in PILL_ICONS},
}

OBSOLETE = tuple(f"data/icons/osg-{name}-symbolic.svg"
                 for name in ("target", "stick", "send", "eye", "curve"))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--check", action="store_true",
                        help="fail if the files differ from this definition")
    args = parser.parse_args(argv)

    root = Path(__file__).resolve().parent.parent
    failed = False
    for rel in OBSOLETE:
        path = root / rel
        if not path.exists():
            continue
        if args.check:
            print(f"should be gone: {rel}", file=sys.stderr)
            failed = True
        else:
            path.unlink()
            print(f"removed {rel}")

    for rel, build in TARGETS.items():
        path = root / rel
        content = build()
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != content:
                print(f"out of date: {rel}", file=sys.stderr)
                failed = True
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {rel}")

    if args.check and not failed:
        print("icons match their definition")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
